### PR TITLE
Corrected abbreviations and other additions

### PR DESCRIPTION
**Pull request by mcmolti**

### CODE REVIEW

**Comment by mcmolti** [comment]
Fixed some mistakes and added additional formatting for easier readability - Malte Scheuvens, Mat.Nr. 01326499

**Comment by mcmolti** [comment]
Only now saw the official process described in TUWEL for fixing errors... can also post a comment once a new issue is opened

**Comment by sebastian-hofstaetter** [comment]
Hi, yes that was not optimal - i merged the other pull request, where your colleague reserved the spot in the issue; if you want you can merge the current main branch into your pull request and see if changes remain, but please be careful not to undo already made corrections - if you still find fixes, you can commit them in your branch of this PR and we can merge them for bonus points afterwards.
Best,
Sebastian

**Comment by sebastian-hofstaetter** [comment]
Hi, great, also merged this request together with the other one.

Best,
Sebastian

**Pull request merged**
